// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	models "github.com/github.com/vido21/dating-app/purchases/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/satori/go.uuid"
)

// PurchaseService is an autogenerated mock type for the PurchaseService type
type PurchaseService struct {
	mock.Mock
}

// FindPurchasePackagedByUserID provides a mock function with given fields: userID
func (_m *PurchaseService) FindPurchasePackagedByUserID(userID uuid.UUID) (*models.Purchase, error) {
	ret := _m.Called(userID)

	var r0 *models.Purchase
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Purchase); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
