// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	models "github.com/github.com/vido21/dating-app/profiles/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/satori/go.uuid"
)

// ProfileService is an autogenerated mock type for the ProfileService type
type ProfileService struct {
	mock.Mock
}

// GetProfileRecomendation provides a mock function with given fields: excludeUserIDs
func (_m *ProfileService) GetProfileRecomendation(excludeUserIDs []uuid.UUID) (*models.Profile, error) {
	ret := _m.Called(excludeUserIDs)

	var r0 *models.Profile
	if rf, ok := ret.Get(0).(func([]uuid.UUID) *models.Profile); ok {
		r0 = rf(excludeUserIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]uuid.UUID) error); ok {
		r1 = rf(excludeUserIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
