// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	common "github.com/github.com/vido21/dating-app/common"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// Routes provides a mock function with given fields:
func (_m *Controller) Routes() []common.Route {
	ret := _m.Called()

	var r0 []common.Route
	if rf, ok := ret.Get(0).(func() []common.Route); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Route)
		}
	}

	return r0
}
