name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker/compose:2.17.2
        options: --entrypoint=docker-compose --env COMPOSE_INTERACTIVE_NO_CLI=1
        ports:
          - 5432:5432
          - 6379:6379
        env:
          POSTGRES_DB: datingapp
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: go1.17.8

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Wait for Services to Start
        run: docker-compose exec -T app sh -c "while ! nc -z database 5432; do sleep 1; done"
        if: always()

      - name: Run Unit Tests
        run: go test ./...

      - name: Stop Docker Compose
        run: docker-compose down
